name: Deploy Vite to GitHub Pages

on:
  push:
    branches: [ main ]   # لو فرعك اسمه غير main بدّله هنا

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      # مهم: ننسخ index.html إلى 404.html لتفادي 404 مع SPA
      - name: SPA fallback
        run: cp dist/index.html dist/404.html

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
